version: '3.7'

services:
  grafana:
    user: root
    container_name: 'max-firstdecent-panel'
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./max-firstdecent-panel:/var/lib/grafana/plugins/max-firstdecent-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      GF_LOG_FILTERS: plugin.max-firstdecent-panel:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: max-firstdecent-panel